### ISSUE TITLE
Index database and wrapper

### ISSUE THREAD

**Issue by vkbo** [metno/MetAlert-Search#3]
Write a Python class to handle inserting and searching a database with indexed data from generated alert files.

The database needs to be able to store:
* Polygon data for predefined areas that can be used in searches.
* An index of UUIDs, datetime, rectangle area and polygon extracted from the raw data.

The class should be able to return:
* Polygons for a specific administrative region.
* A list of UUIDs and polygons that matches a rectangle on rectangle intersect.

**Comment by fzeiser** [comment]
- [ ] Add information on coordinate system in DB
- [ ] Storage format: geoJSON?
